/** The full legacy dropdown list (web/index.html #ac-select) — always offered, even when not
 * currently visible above the horizon, unlike the API's `visible`-only set. */
export const ALL_CONSTELLATIONS = [
  { abbr: "Sco", name: "Scorpius", emoji: "🦂" },
  { abbr: "UMa", name: "Ursa Major", emoji: "🐻" },
  { abbr: "Ori", name: "Orion", emoji: "🏹" },
  { abbr: "Cas", name: "Cassiopeia", emoji: "👑" },
  { abbr: "Cyg", name: "Cygnus", emoji: "🦢" },
  { abbr: "Cru", name: "Crux", emoji: "✝️" },
  { abbr: "CMa", name: "Canis Major", emoji: "🐕" },
  { abbr: "CMi", name: "Canis Minor", emoji: "🐩" },
  { abbr: "Cen", name: "Centaurus", emoji: "🐎" },
  { abbr: "Ari", name: "Aries", emoji: "♈" },
  { abbr: "Tau", name: "Taurus", emoji: "♉" },
  { abbr: "Gem", name: "Gemini", emoji: "♊" },
  { abbr: "Aur", name: "Auriga", emoji: "🔶" },
  { abbr: "Per", name: "Perseus", emoji: "⚔️" },
  { abbr: "Cnc", name: "Cancer", emoji: "♋" },
  { abbr: "Leo", name: "Leo", emoji: "♌" },
  { abbr: "LMi", name: "Leo Minor", emoji: "🦁" },
  { abbr: "Vir", name: "Virgo", emoji: "♍" },
  { abbr: "Lib", name: "Libra", emoji: "♎" },
  { abbr: "Sgr", name: "Sagittarius", emoji: "♐" },
  { abbr: "Cap", name: "Capricornus", emoji: "♑" },
  { abbr: "Aqr", name: "Aquarius", emoji: "♒" },
  { abbr: "Psc", name: "Pisces", emoji: "♓" },
  { abbr: "Mon", name: "Monoceros", emoji: "🦄" },
  { abbr: "Lyn", name: "Lynx", emoji: "🐱" },
  { abbr: "Lep", name: "Lepus", emoji: "🐇" },
  { abbr: "Cam", name: "Camelopardalis", emoji: "🦒" },
  { abbr: "Pup", name: "Puppis", emoji: "⛵" },
  { abbr: "Col", name: "Columba", emoji: "🕊️" },
] as const;
