import type { PlanetDef } from "@/types";

export const TEX_BASE = "/assets/";

export const PLANETS: PlanetDef[] = [
  {
    name: "Sun",
    radius: 10,
    orbitRadius: 0,
    speed: 0,
    color: 0xffcc33,
    emissive: 0xffaa00,
    emissiveIntensity: 4.0,
    textureUrl: `${TEX_BASE}2k_sun.jpg`,
  },
  {
    name: "Mercury",
    radius: 1.5,
    orbitRadius: 26,
    speed: 0.018,
    color: 0x8c7e6d,
    emissive: 0x1a1510,
    textureUrl: `${TEX_BASE}mercury.jpg`,
  },
  {
    name: "Venus",
    radius: 2.2,
    orbitRadius: 38,
    speed: 0.012,
    color: 0xc8a878,
    emissive: 0x1a1408,
    textureUrl: `${TEX_BASE}venus.jpg`,
  },
  {
    name: "Earth",
    radius: 2.3,
    orbitRadius: 52,
    speed: 0.01,
    color: 0x4488cc,
    emissive: 0x0a1020,
    textureUrl: `${TEX_BASE}2k_earth_daymap.jpg`,
  },
  {
    name: "Mars",
    radius: 1.8,
    orbitRadius: 68,
    speed: 0.008,
    color: 0xb85a3a,
    emissive: 0x1a0800,
    textureUrl: `${TEX_BASE}mars.jpg`,
  },
  {
    name: "Jupiter",
    radius: 5.5,
    orbitRadius: 95,
    speed: 0.004,
    color: 0xc8a878,
    emissive: 0x1a1408,
    textureUrl: `${TEX_BASE}jupiter.jpg`,
  },
  {
    name: "Saturn",
    radius: 4.5,
    orbitRadius: 125,
    speed: 0.003,
    color: 0xd8c898,
    emissive: 0x1a1508,
    textureUrl: `${TEX_BASE}saturn.jpg`,
    ringInner: 6.0,
    ringOuter: 10.0,
  },
  {
    name: "Uranus",
    radius: 3.2,
    orbitRadius: 155,
    speed: 0.002,
    color: 0x78b8c8,
    emissive: 0x0a1520,
    textureUrl: `${TEX_BASE}uranus.jpg`,
  },
  {
    name: "Neptune",
    radius: 3.0,
    orbitRadius: 180,
    speed: 0.001,
    color: 0x3355bb,
    emissive: 0x050a20,
    textureUrl: `${TEX_BASE}neptune.jpg`,
  },
];
